title: DarkOrbit Pixel Bot
description: >-
  The game bot former known as the "new PBDO-BOT" is now a free opensource DarkOrbit pixel bot.
  Out bot script collects bonus boxes automatically while managing your ship and PET.
  Stop wasting time grinding, use our bot instead to get extra Uridium and Extra Energy.
url: "https://pbdo-bot.net/"
lang: en_US

botfather_link: https://botfather.io/downloads
github_link: https://github.com/Dementor42/darkorbit-pixel-bot/
discord_link: https://discord.gg/MeVvkdf

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: "page"